######################################################################
# Automatically generated by qmake (2.01a) Tue Oct 21 11:52:27 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
