######################################################################
# Automatically generated by qmake (2.01a) Tue Oct 21 12:11:38 2008
######################################################################

TEMPLATE = app
QT += network xml gui
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp

